package registrydesignpattern;

public class Designs {

    public static final String DESIGN_SPIDERMAN="Spiderman";
    public static final String DESIGN_BATMAN="Batman";

    public static final String DESIGN_SUPERMAN="Superman";
    public static final String DESIGN_THOR="THOR";
    public static final String DESIGN_MERCEDES="Mercedes";
    public static final String DESIGN_TOM_JERRY="Tom&Jerry";
    public static final String DESIGN_POKEYMON="PokeyMon";
    public static final String DESIGN_CAIPTAN_AMERICA="Caiptan America";

    public static final String[] designs={DESIGN_BATMAN,DESIGN_MERCEDES,DESIGN_POKEYMON,DESIGN_THOR,DESIGN_SPIDERMAN
    ,DESIGN_CAIPTAN_AMERICA,DESIGN_TOM_JERRY,DESIGN_SUPERMAN,DESIGN_BATMAN,DESIGN_MERCEDES,DESIGN_POKEYMON,DESIGN_THOR,DESIGN_SPIDERMAN
    ,DESIGN_CAIPTAN_AMERICA,DESIGN_TOM_JERRY,DESIGN_SUPERMAN,DESIGN_BATMAN,DESIGN_MERCEDES,DESIGN_POKEYMON,DESIGN_THOR,DESIGN_SPIDERMAN
    ,DESIGN_CAIPTAN_AMERICA,DESIGN_TOM_JERRY,DESIGN_SUPERMAN,DESIGN_BATMAN,DESIGN_MERCEDES,DESIGN_POKEYMON,DESIGN_THOR,DESIGN_SPIDERMAN
    ,DESIGN_CAIPTAN_AMERICA,DESIGN_TOM_JERRY,DESIGN_SUPERMAN,DESIGN_BATMAN,DESIGN_MERCEDES,DESIGN_POKEYMON,DESIGN_THOR,DESIGN_SPIDERMAN
    ,DESIGN_CAIPTAN_AMERICA,DESIGN_TOM_JERRY,DESIGN_SUPERMAN,DESIGN_BATMAN,DESIGN_MERCEDES,DESIGN_POKEYMON,DESIGN_THOR,DESIGN_SPIDERMAN
    ,DESIGN_CAIPTAN_AMERICA,DESIGN_TOM_JERRY,DESIGN_SUPERMAN,DESIGN_BATMAN,DESIGN_MERCEDES,DESIGN_POKEYMON,DESIGN_THOR,DESIGN_SPIDERMAN
    ,DESIGN_CAIPTAN_AMERICA,DESIGN_TOM_JERRY,DESIGN_SUPERMAN,DESIGN_BATMAN,DESIGN_MERCEDES,DESIGN_POKEYMON,DESIGN_THOR,DESIGN_SPIDERMAN
    ,DESIGN_CAIPTAN_AMERICA,DESIGN_TOM_JERRY,DESIGN_SUPERMAN,DESIGN_BATMAN,DESIGN_MERCEDES,DESIGN_POKEYMON,DESIGN_THOR,DESIGN_SPIDERMAN
    ,DESIGN_CAIPTAN_AMERICA,DESIGN_TOM_JERRY,DESIGN_SUPERMAN,DESIGN_BATMAN,DESIGN_MERCEDES,DESIGN_POKEYMON,DESIGN_THOR,DESIGN_SPIDERMAN
    ,DESIGN_CAIPTAN_AMERICA,DESIGN_TOM_JERRY,DESIGN_SUPERMAN,DESIGN_BATMAN,DESIGN_MERCEDES,DESIGN_POKEYMON,DESIGN_THOR,DESIGN_SPIDERMAN
    ,DESIGN_CAIPTAN_AMERICA,DESIGN_TOM_JERRY,DESIGN_SUPERMAN};

}
